### PR TITLE
Version 0.32.3

### LINKED ISSUE #175: Change the addon to Extension
And eventually release it on: https://extensions.blender.org

User guide: https://docs.blender.org/manual/en/4.2/advanced/extensions/getting_started.html#manifest

### PR DESCRIPTION
**Pull request by Mustard2**
Close #175

### CODE REVIEW

**Comment by cl3m3c7** [comment]
is it time to remove those `if version < 4.1` checks?

**Comment by Mustard2** [comment]
> is it time to remove those `if version < 4.1` checks?

Yes, and I'm not even sure the updater is necessary now. If I manage to get the Blender extension on the official repo, the updates will be managed by Blender itself.

**Comment by Mustard2** [comment]
Rebased on master

**Comment by Mustard2** [comment]
Planned to be released when approved on the Blender Extensions website

**Comment by Mustard2** [comment]
Added:
- Feature: Armature Presets for MHX armatures
- Feature: Armature Visibility Reset button (to reset the visible collections to the default ones, that can be set in the Configuration mode)

**Pull request merged**
